name: Buil Workflow
on:
  pull_request:
    branches: [atb-cehck]
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches: [atb-cehck]

jobs:
  main:
    runs-on: runner
    env:
      AWS_ROLE: "arn:aws:iam::357022024302:role/Builder"
    if: github.base_ref == 'master' || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Run the docekr build and push the image to registry
        run: |
          chmod +x ./bin/cac.sh
          ./bin/cac.sh
