name: Build Workflow
on:
  pull_request:
    branches: [master,dev,pre]
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches: [master,dev,pre]

jobs:
  main:
    runs-on: runner
    env:
      AWS_ROLE: "arn:aws:iam::357022024302:role/builder"
    if: github.base_ref == 'master' || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Run the docekr build and push the image to registry
        run: |
         docker build -t spring --build-arg version="1.2" .
